### ISSUE TITLE
Too many open files - ZMQerror

### ISSUE THREAD

**Issue by xraysmile** [honeynet/beeswarm#230]
Hi,

I get this error - see screeshot ->

![beeswarm_to_many_open_files](https://cloud.githubusercontent.com/assets/13118457/19471722/c9055d46-9524-11e6-8c3b-b4bd9bd5cb73.PNG)

 when im using the client bait. It occours after 2-3 days run time.

Any idea to handle this except for restarting every 24 hour?

Best regards

**Comment by johnnykv** [comment]
This does not seem to be a ZeroMQ problem, but rather a problem in one (or more) of the beeswarm capabilities. I will take a look at it, when I get time.

**Comment by johnnykv** [comment]
@xraysmile are you seeing this on a honeypot or client drone?

**Comment by czardoz** [comment]
Going by the traceback, seems to be the honeypot. A quick workaround would be to increase the limit of number of open files: http://unix.stackexchange.com/questions/8945/how-can-i-increase-open-files-limit-for-all-processes

If @xraysmile keeps running into this issue (even after increasing the open file limit), there's a good chance we're leaking open connections somewhere, @johnnykv

**Comment by johnnykv** [comment]
@czardoz yeah, think i might have found the leak... Trying to figure if occurs in all modes... Tricky debugging :-)

**Comment by xraysmile** [comment]
I see it both on the client and honeypot

**Comment by johnnykv** [comment]
fixed as of 7dd8fe1
