### ISSUE TITLE
Lost the admin password after reboot

### ISSUE THREAD

**Issue by bartoch** [honeynet/beeswarm#237]
Hello,

After the install i have the password admin, i can open the session, all it's ok but if i reboot the server.

I start it with:
--server --workdir /home/user/server_workdir

The server running but i can't log in.

I reinsatll all, i have a new password but always the same problem if i reboot.

thx,

**Comment by gnomefish** [comment]
I'm having the same with these errors

::ffff:192.168.1.2 - - [2017-01-30 21:08:48] "POST /login?next=%2F HTTP/1.1" 200 2566 0.002980
::ffff:192.168.1.2 - - [2017-01-30 21:09:05] "GET / HTTP/1.1" 302 703 0.002238
/usr/local/lib/python2.7/dist-packages/beeswarm/server/webapp/app.py:142: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form = LoginForm()

**Comment by AliLazy** [comment]
I am facing same issue .... Anyone resolve this issue ?

**Comment by johnnykv** [comment]
you can reset the admin password using the --resetpw option.

**Comment by AliLazy** [comment]
Where I find rest password option?
